set log file fv/riscv_tcm_wrapper/rtl_to_g1_withoutovf.log -replace
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1
tclmode
set env(RC_VERSION) "v12.10-s012_1"
vpxmode
set dofile abort exit
usage -auto -elapse
// tclmode
// set env(CDN_SYNTH_ROOT) /home/buet/cadence/EDI/tools
// vpxmode
tclmode
set ver [lindex [split [lindex [get_version_info] 0] "-"] 0]
if {$ver >= 08.10} {
  vpx set naming style rc
}
vpxmode
set naming rule "%s[%d]" -instance_array
set naming rule "%s_reg" -register -golden
set naming rule "%L.%s" "%L[%d].%s" "%s" -instance
set naming rule "%L.%s" "%L[%d].%s" "%s" -variable
set undefined cell black_box -noascend -both
set undriven signal Z -golden
add notranslate modules -library -both \
	MEM2_2048X32


add search path -library /home/buet/cadence/EDI/share/FoundationFlows/EXAMPLES/PROTO/LIBS/GPDK/LIBS/GPDK045/timing
read library -statetable -liberty -both  \
	slow.lib \
	MEM2_2048X32_slow.lib

add search path -design /home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core /home/buet/Documents/RISCV32I_TCM_AXI/RTL/top_tcm_wrapper
read design  -verilog2k -define SYNTHESIS  -golden -lastmod -noelab \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_defs.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_alu.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_exec.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_decoder.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_decode.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_fetch.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_pipe_ctrl.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_regfile.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_csr_regfile.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_csr.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_divider.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_multiplier.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_lsu.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_mmu.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_issue.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/riscv_core/riscv_core.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/top_tcm_wrapper/dport_axi.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/top_tcm_wrapper/dport_mux.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/top_tcm_wrapper/tcm_mem_ram.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/top_tcm_wrapper/tcm_mem_pmem.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/top_tcm_wrapper/tcm_mem.v \
	/home/buet/Documents/RISCV32I_TCM_AXI/RTL/top_tcm_wrapper/riscv_tcm_wrapper.v

elaborate design -golden -root riscv_tcm_wrapper -rootonly \

read design -verilog -revised -lastmod -noelab \
	-unzip fv/riscv_tcm_wrapper/g1.v.gz

elaborate design -revised -root riscv_tcm_wrapper

substitute blackbox model -golden
report design data
report black box

uniquify -all -nolib
set flatten model -seq_constant -seq_constant_x_to 0
set flatten model -nodff_to_dlat_zero -nodff_to_dlat_feedback
// set parallel option -threads 4 -license xl -norelease_license
// set compare options -threads 0
set analyze option -auto

write hier_compare dofile fv/riscv_tcm_wrapper/hier_rtl_to_g1_withoutovf.do \
	-noexact_pin_match -constraint -usage -replace -balanced_extraction -input_output_pin_equivalence \
	-prepend_string "analyze datapath -module -verbose; usage; analyze datapath -verbose"
run hier_compare fv/riscv_tcm_wrapper/hier_rtl_to_g1_withoutovf.do -analyze_abort  -dynamic_hierarchy
// report hier_compare result -dynamicflattened
set system mode lec
tclmode
puts "No of diff points    = [get_compare_points -diff -count]"
if {[get_compare_points -diff -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
#     foreach i [get_compare_points -diff] {
#         vpx report test vector [get_keypoint $i]
#         puts "     ----------------------------"
#     }
}
vpxmode
exit -force
